base:
  normalize: False
  bs: 32
  epochs: 50
  model: resnet18

norm:
  normalize: True
  bs: 32
  epochs: 50
  model: resnet18

coord:
  normalize: False
  bs: 32
  epochs: 50
  model: spatial_resnet18

normAndCoord:
  normalize: True
  bs: 32
  epochs: 50
  model: spatial_resnet18

normAndCoordAndMLP2:
  normalize: True
  bs: 32
  epochs: 50
  model: spatial_mlp2_resnet18

normAndCoordAndSquare:
  normalize: True
  bs: 32
  epochs: 50
  model: spatial_square_resnet18

normAndCoordAndFPN:
  normalize: True
  bs: 32
  epochs: 50
  model: spatial_fpn_resnet18

globalMod:
  normalize: True
  bs: 32
  epochs: 50
  model: spatial_global_resnet18